version: '3'
services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-vue-app
    container_name: vue-app

  nginx-server:
    image: nginx:stable-alpine
    ports:
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/usr/share/nginx/html
