version: '3'
services:
  # first service for application
  intern-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: build-stage
    image: intern-app # application image name
    container_name: inter-app-docker-container # application container name
    
  # second service for nginx server
  nginx-server:
    build: 
      context: .
      dockerfile: Dockerfile
      target: production-stage
    ports:
      - "443:443"
    image: intern-server-docker-image # server image name
    container_name: intern-server-docker-container # server container name
 