version: '3'
services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: build-stage
    image: my-vue-app
    container_name: vue-app

  nginx-server:
    build: 
      context: .
      dockerfile: Dockerfile
      target: production-stage
    ports:
      - "443:443"
